// reactapp-pfm/src/components/CreditCard_Transaction/CreditCard_Transaction.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import { getCCTypeColor } from "../../services/local.service";
import BankTransactionService from "../../services/bank.transaction.service";
import CCService from "../../services/cc.service";

import { useNavigate, useLocation } from "react-router";

import Moment from "moment";
const CreditCard_Transaction = () => {
  let navigate = useNavigate();

  const { state } = useLocation();
  const { creditCardId, balance, ccAccountNumber, creditCardName } =
    state || {}; // Read values passed on state

  const [payees, setPayees] = useState([]);
  const [modelErrors, setModelErrors] = useState([]);
  const [ccTrAddCreateResponse, setCcTrAddCreateResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  // reset form
  // form reference
  const formRef = useRef(null);

  useEffect(() => {
    if (creditCardId === undefined || balance === undefined)
      navigate("/creditcard");

    listOfPayees();
  }, []);

  const listOfPayees = () => {
    BankTransactionService.listOfPayees()
      .then((response) => {
        setPayees(response.data.filter((xx) => xx.payeeType !== 3));
        console.log(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const goBack = (e) => {
    navigate("/creditcard/");
  };

  const setField = (field, value) => {
    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const { payeeId, transactionAmount, transactionDate } = form;
    const newErrors = {};

    if (!payeeId || payeeId === "") newErrors.payeeId = "Payee is Required!";
    if (!transactionDate || transactionDate === "")
      newErrors.transactionDate = "Transaction Date is Required!";

    if (!transactionAmount || transactionAmount === "")
      newErrors.transactionAmount = "Transaction Amount is Required!";

    if (!(!transactionAmount || transactionAmount === "")) {
      if (!checkForNumbersOnly(transactionAmount))
        newErrors.transactionAmount = "Only Numbers are Allowed!";
    }
    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      if (error.response.data.status === 400) {
        console.log("Bad Request!!!");
        errors.push(error.response.statusText + " !");
      } else {
        for (let prop in error.response.data) {
          if (error.response.data[prop].length > 1) {
            for (let error_ in error.response.data[prop]) {
              errors.push(error.response.data[prop][error_]);
            }
          } else {
            errors.push(error.response.data[prop]);
          }
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };
  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setCcTrAddCreateResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var ccTransaction = {
        payeeId: Number(form.payeeId),
        transactionAmount: Number(form.transactionAmount),
        transactionDate: form.transactionDate,
        creditCardId: Number(creditCardId),
        balance: Number(balance),
        ccAccountNumber: ccAccountNumber,
      };

      console.log(ccTransaction);

      // api call
      CCService.addCCTransaction(ccTransaction)
        .then((response) => {
          setModelErrors([]);
          setCcTrAddCreateResponse({});
          console.log(response.data);

          var trCreateResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };
          if (response.data.responseCode === 0) {
            resetForm();
            setCcTrAddCreateResponse(trCreateResponse);

            setTimeout(() => {
              navigate("/creditcard/");
            }, 3000);
          } else if (response.data.responseCode === -1) {
            setCcTrAddCreateResponse(trCreateResponse);
          }
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setCcTrAddCreateResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };
  const renderOptionsForPayees = () => {
    return payees.map((dt, i) => {
      return (
        <option value={dt.payeeId} key={i} name={dt.payeeName}>
          {dt.payeeName}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-8 mx-auto">
            <div className="card">
              <div
                style={{
                  backgroundColor: getCCTypeColor(creditCardName),
                }}
                className="card-header"
              >
                <div className="row">
                  <div className="col-md-10 mx-auto">
                    <h4>Add Your Transaction Here...</h4>
                    <h5>[ From Credit-Card ---&gt; Payee ]</h5>
                    <div className="ccHeader">
                      Credit-Card : {creditCardName}
                      <br />
                      CC A/C Number : {ccAccountNumber}
                      <br />
                      Maximum Pay : {balance}
                    </div>
                  </div>
                  <div className="col-md-2 mx-auto">
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => goBack(e)}
                    >
                      <i className="bi bi-arrow-return-left"></i> Back
                    </Button>
                  </div>
                </div>
                <p></p>
                {ccTrAddCreateResponse &&
                ccTrAddCreateResponse.responseCode === -1 ? (
                  <span className="ccTrAddCreateError">
                    {ccTrAddCreateResponse.responseMessage}
                  </span>
                ) : (
                  <span className="ccTrAddCreateSuccess">
                    {ccTrAddCreateResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="payeeId">
                        <Form.Label>Payee</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.payeeId}
                          onChange={(e) => {
                            setField("payeeId", e.target.value);
                          }}
                        >
                          <option value="">Select Payee</option>
                          {renderOptionsForPayees()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.payeeId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <Form.Group controlId="transactionAmount">
                        <Form.Label>Amount</Form.Label>
                        <Form.Control
                          className="qtyField"
                          type="text"
                          isInvalid={!!errors.transactionAmount}
                          onChange={(e) =>
                            setField("transactionAmount", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.transactionAmount}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Label>Transaction Date</Form.Label>
                      <Form.Control
                        type="date"
                        name="transactionDate"
                        placeholder="Transaction Date"
                        isInvalid={!!errors.transactionDate}
                        onChange={(e) =>
                          setField("transactionDate", e.target.value)
                        }
                      />
                      <Form.Control.Feedback type="invalid">
                        {errors.transactionDate}
                      </Form.Control.Feedback>
                    </div>
                  </div>
                  <p></p>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                    }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Commit Transaction
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Cancel
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CreditCard_Transaction;

// Angular/src/app/credit-card-transaction/credit-card-transaction.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import { ActivatedRoute, Router } from '@angular/router';
import CreditCardTransaction from '../models/creditCardTransaction';
import PayeeType from '../models/payeeType';
import Payee from '../models/payee';

@Component({
  selector: 'app-credit-card-transaction',
  templateUrl: './credit-card-transaction.component.html',
  styleUrls: ['./credit-card-transaction.component.css']
})
export class CreditCardTransactionComponent implements OnInit {

  ccTransaction: CreditCardTransaction;
  payees: Payee[];

  transactionForm: FormGroup;
  submitted = false;

  ccColor = '';
  apiResponse = '';
  responseColor = '';
  errors: string[];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.ccTransaction = new CreditCardTransaction();
    this.ccTransaction = this.localDataService.getCCTransaction();
    if (!this.ccTransaction.creditCardId) {
      this.router.navigate(['/creditcard']);
    }

    this.ccColor = this.ccTransaction.ccColor;

    this.errors = [];
    this.payees = [];

    this.loadPayees();    

    this.transactionForm = this.fb.group({
      PayeeId: ['', Validators.required],
      TransactionAmount: ['', Validators.required],
      TransactionDate: ['', Validators.required]
    });
  }

  // ok
  loadPayees() {
    this.dataService.listOfPayees()
      .subscribe(
        data => {
          this.payees = data;
          this.payees = this.payees.filter(xx => xx.payeeType != 3);          
        },
        error => {
          console.log(error);
        });
  }

  resetCCTransaction() {
    this.apiResponse = '';
    this.transactionForm.reset();
    this.transactionForm.get("PayeeId").patchValue('');
    this.submitted = false;
    this.errors = [];
    this.responseColor = '';

    // to prevent back history
    this.ccTransaction = new CreditCardTransaction();
    this.localDataService.setCCTransaction(this.ccTransaction);
  }

  addCCTransaction() {
    this.submitted = true;
    if (this.transactionForm.valid) {
      this.ccTransaction.payeeId = Number(this.transactionForm.value["PayeeId"]);
      this.ccTransaction.transactionAmount = Number(this.transactionForm.value["TransactionAmount"]);
      this.ccTransaction.transactionDate = new Date(this.transactionForm.value["TransactionDate"].year + '/' + this.transactionForm.value["TransactionDate"].month + '/' + this.transactionForm.value["TransactionDate"].day);

      console.log(this.ccTransaction);

      /*
      this.dataService.addCCTransaction(this.ccTransaction)
        .subscribe(
          response => {
            if (response.responseCode == 0) {
              // success    
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.errors = [];

              this.transactionForm.reset();
              this.transactionForm.get("PayeeId").patchValue('');
              this.submitted = false;

              setTimeout(() => {
                this.router.navigate(['/creditcard']);
                this.apiResponse = '';
              }, 3000);
            }
            else {
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';

              this.errors = [];
            }
            // to prevent back history
            this.ccTransaction = new CreditCardTransaction();
            this.localDataService.setCCTransaction(this.ccTransaction);
          },
          error => {
            this.apiResponse = '';
            this.responseColor = 'red';
            this.errors = [];

            // to prevent back history
            this.ccTransaction = new CreditCardTransaction();
            this.localDataService.setCCTransaction(this.ccTransaction);

            this.errors = this.localDataService.display400andEx(error, 'Credit-Card-Transaction');
          }
        );
        */
    }
  }

  // ok
  public handleError = (controlName: string, errorName: string) => {
    return this.transactionForm.controls[controlName].hasError(errorName);
  }

  // ok
  get transactionFormControl() {
    return this.transactionForm.controls;
  }

  // ok
  goBack() {
    this.ccTransaction = new CreditCardTransaction();
    this.localDataService.setCCTransaction(this.ccTransaction);
    this.router.navigate(['/creditcard']);
  }

  // ok
  // disable browser history
  ngOnDestroy() {
    this.ccTransaction = new CreditCardTransaction();
    this.localDataService.setCCTransaction(this.ccTransaction);
  }
}

<div class="container main-container">
    <div>
        <h2>
            Manage Credit-Card / Transaction
        </h2>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header" 
                    [ngStyle]="{'background-color': ccColor}">
                    <h3>
                        <div class="row">
                            <div class="col-md-4 mx-auto">
                                <button type="button" 
                                    (click)="goBack()" 
                                    class="btn btn-primary">
                                    <i class="bi bi-backspace-fill"> Cancel</i>
                                </button>
                            </div>
                            <div class="col-md-8 mx-auto add-cc-transaction-header">
                                Add Your Transaction here...
                            </div>
                        </div>
                    </h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <h6 class="maximumCredit" 
                                *ngIf="ccTransaction.creditCardId">
                                <span>
                                    Credit Card : {{ccTransaction.ccAccountNumber}}
                                    <p></p>
                                    Maximum Credit Available : ${{ccTransaction.balance}}
                                </span>
                            </h6>
                        </div>
                    </div>
                    <h4 *ngIf="apiResponse">
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                        <hr />
                    </h4>
                    <h5 *ngIf="errors.length > 0">
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of errors">
                                {{ error }}
                            </li>
                        </ul>
                        <hr />
                    </h5>

                </div>
                <div class="card-body">
                    <form class="form-payee"    
                        [formGroup]="transactionForm">   
                        <div class="form-group">
                            <div class="row mb-2">
                                <label for="PayeeId" 
                                    class="col-sm-2 col-form-label">
                                    Payee
                                </label>
                                <div class="col-sm-5">
                                    <select class="form-control" 
                                        formControlName="PayeeId">
                                        <option disabled>Select Payee</option>
                                        <option value="">Choose Payee</option>
                                        <option value="{{p.payeeId}}" 
                                            *ngFor="let p of payees">
                                            {{p.payeeName}}
                                        </option>
                                    </select>
                                </div>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.PayeeId.touched || submitted) && handleError('PayeeId', 'required')">
                                    Payee is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="TransactionAmount"                                     
                                    class="col-sm-2 col-form-label">
                                    Amount
                                </label>
                                <div class="col-sm-5">
                                    <input type="text" 
                                        class="form-control" 
                                        formControlName="TransactionAmount">
                                </div>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.TransactionAmount.touched || submitted) && transactionFormControl.TransactionAmount.errors?.required">
                                    Transaction Amount is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group datepicker">
                            <div class="row mb-3">
                                <label for="TransactionDate"                                     
                                    class="col-sm-2 col-form-label">Date</label>
                                <div class="col-sm-5">
                                    <div class="row">
                                        <div class="col-sm-8">
                                            <input class="form-control" 
                                                placeholder="yyyy-mm-dd" 
                                                name="dp"
                                                formControlName="TransactionDate" 
                                                ngbDatepicker #d="ngbDatepicker">
                                        </div>
                                        <div class="col-sm-4">
                                            <span class="input-group-append">
                                                <button class="btn btn-outline-secondary calendar" 
                                                    (click)="d.toggle()"
                                                    type="button">
                                                    <i class="bi bi-calendar-check-fill"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.TransactionDate.touched || submitted) && transactionFormControl.TransactionDate.errors?.required">
                                    Transaction Date is required!
                                </span>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.TransactionDate.touched || submitted) && !transactionFormControl.TransactionDate.valid && !transactionFormControl.TransactionDate.errors?.required ">
                                    Invalid Transaction Date !
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-4">
                            <button type="button" (click)="addCCTransaction()" 
                                class="btn btn-success">
                                Commit Transaction
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button type="button" 
                                (click)="resetCCTransaction()" 
                                class="btn btn-primary">
                                Reset
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
