// Angular/src/app/account/account.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import Bank from '../models/bank';
import { Observable } from 'rxjs';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import Account from '../models/account';
import AccountType from '../models/accountType';

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css']
})
export class AccountComponent implements OnInit {

  accounts: Account[];
  accountTypesName: string[];
  accountTypesCollection: AccountType[];

  constructor(public localDataService: LocalDataService, public dataService: DataService, private router: Router) { }

  // ok
  ngOnInit() {
    this.accounts = [];
    this.accountTypesName = [];
    this.accountTypesCollection = [];

    this.loadAccountTypes();
    this.loadAccounts();
  }

  // ok
  loadAccountTypes() {
    this.dataService.getAccountTypes()
      .subscribe(
        data => {
          this.accountTypesName = data;
          this.accountTypesCollection = this.localDataService.getAccountTypeCollection(this.accountTypesName);
        },
        error => {
          console.log(error);
        });
  }
  // ok
  displayAccountType(accountType) {
    if (this.accountTypesCollection != null) {
      return this.accountTypesCollection[accountType].accountType;
    }
    else {
      return 0;
    }
  }

  // ok
  bankRowSetup(accounts) {
    accounts.forEach((element) => {
      element.bgColor = this.localDataService.getBankColor(element.bankName);
    });
  }

  // ok
  loadAccounts() {
    this.dataService.getAccounts()
      .subscribe(
        data => {
          this.accounts = data;
          
          // bank name wise color setup
          this.bankRowSetup(this.accounts);

          // accounts sort by bank name
          this.accounts.sort((a, b) => a.bankName.localeCompare(b.bankName));          
        },
        error => {
          console.log(error);
        });
  }

  // ok
  editAccount(editAccount) {
    // redirect to account-edit component
    // this.router.navigate(['/account-edit/' + editAccount.accountId]);
    this.router.navigate(['/account-edit/', { selectedAccountObject: JSON.stringify(editAccount) }]);
  }

  // ok
  removeAccount(account) {
    console.log(account);
  }

  // ok
  addAccount() {
    // redirect to account-add component
    this.router.navigate(['/account-add']);

  }
}

<div class="container main-container">
    <div>
        <h2>
            Manage Accounts
        </h2>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="card-header header-bg-color">
                    <button type="button" 
                        class="btn btn-primary" 
                        (click)="addAccount()">
                        <i class="bi bi-plus-circle"> Account</i>
                    </button>
                </div>
                <div *ngIf="(accounts?.length > 0)" class="card-body">
                    <table class="table table-text ">
                        <thead class="table-header-text">
                            <tr>                              
                                <th>A/C Number</th>
                                <th>Type</th>
                                <th>Bank</th>
                                <th>Balance</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr [ngStyle]="{'background-color': a.bgColor}" 
                                *ngFor="let a of accounts">
                                <td>
                                    <h2><i class="bi bi-bag">{{a.accountNumber}}</i></h2>
                                </td>
                                <td [style.color]="localDataService.getAccountTypeColor(a.accountType)">{{displayAccountType(a.accountType)}}</td>
                                <td>
                                    {{a.bankName}}
                                </td>
                                <td>{{a.balance}}</td>
                                <td>
                                    <div class="row">
                                        <div class="col-1"></div>
                                        <div class="col-4">
                                            <button type="button" 
                                                (click)="editAccount(a)" 
                                                class="btn btn-primary">
                                                <i class="bi bi-pencil-fill"></i>
                                            </button>
                                        </div>
                                        <div class="col-1"></div>
                                        <div class="col-4">
                                            <button type="button" 
                                                (click)="removeAccount(a)" 
                                                class="btn btn-danger">
                                                <i class="bi bi-trash-fill"></i>
                                            </button>
                                        </div>
                                        <div class="col-8"></div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div *ngIf="!(accounts?.length > 0)" class="card-body no-account">
                    No Accounts Yet !!!
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-pfm/src/components/Account/Account.jsx
import React, { useState, useEffect } from "react";
import "./style.css";
import AccountService from "../../services/account.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import Button from "react-bootstrap/Button";

import {
  getBankColor,
  getAccountType,
  getAccountColor,
} from "../../services/local.service";

const Account = () => {
  let navigate = useNavigate();

  const [accounts, setAccounts] = useState([]);

  useEffect(() => {
    getAllAccounts();
  }, []);
  const getAllAccounts = () => {
    AccountService.allAccounts()
      .then((response) => {
        // accounts sort by bank name
        response.data.sort((a, b) => a.bankName.localeCompare(b.bankName));
        setAccounts(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  const getBankStyle = (row, rowIdx) => {
    var bankColor = getBankColor(row.bankName);
    return { backgroundColor: bankColor };
  };

  const displayAcType = (cell, row) => {
    return (
      <div>
        <b>
          <span style={{ color: `${getAccountColor(cell)}` }}>
            {getAccountType(cell)}
          </span>
        </b>
      </div>
    );
  };
  const displayAccountNumber = (cell, row) => {
    return (
      <div>
        <span>
          <i className="bi bi-bag"></i> {cell}
        </span>
      </div>
    );
  };
  const displayActionBtn = (cell, row) => {
    return (
      <div>
        {" "}
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => editAccount(e, row.accountId)}
        >
          <i className="bi bi-pencil-square"></i>
        </Button>{" "}
        <Button
          className="btn btn-danger"
          type="button"
          onClick={(e) => removeAccount(e, row.accountId)}
        >
          <i className="bi bi-trash"></i>
        </Button>
      </div>
    );
  };
  const editAccount = (e, accountId) => {
    console.log("edit account : ", accountId);
    navigate("/account-edit/" + accountId);
  };
  const removeAccount = (e, accountId) => {};
  const createNewAccount = () => {
    navigate("/account-create");
  };

  const columns = [
    {
      dataField: "accountNumber",
      text: "A/C Number",
      sort: true,
      formatter: (cell, row) => displayAccountNumber(cell, row),
    },
    {
      dataField: "accountType",
      text: "Type",
      sort: true,
      formatter: (cell, row) => displayAcType(cell, row),
    },
    {
      dataField: "bankName",
      text: "Bank",
    },
    {
      dataField: "balance",
      text: "Balance",
    },
    {
      dataField: "actions",
      text: "Actions",
      formatter: (cell, row) => displayActionBtn(cell, row),
    },
  ];
  return (
    <div className="container">
      <div className="mainHeader">Accounts</div>
      <hr />
      <div className="row">
        <div className="col-md-2 mx-auto"></div>
        <div className="col-md-8 mx-auto">
          <Button
            className="btn btn-primary"
            type="button"
            onClick={(e) => createNewAccount(e)}
          >
            <i className="bi bi-plus-circle"></i> Account
          </Button>
          <p></p>
          {accounts && accounts.length > 0 ? (
            <BootstrapTable
              bootstrap4
              keyField="accountId"
              data={accounts}
              rowStyle={getBankStyle}
              columns={columns}
              pagination={paginationFactory({ sizePerPage: 5 })}
              filter={filterFactory()}
            />
          ) : (
            <div className="noAccounts">No Accounts!</div>
          )}
        </div>
        <div className="col-md-2 mx-auto"></div>
      </div>
    </div>
  );
};

export default Account;
