// reactapp-pfm/src/components/Account_Edit/Account_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import { getBankColor } from "../../services/local.service";
import BankService from "../../services/bank.service";
import AccountService from "../../services/account.service";

import { useNavigate } from "react-router";

import Moment from "moment";
import accountHttpCommon from "../../axios/account-http-common";

const Account_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [accountTypes, setAccountTypes] = useState([]);
  const [banks, setBanks] = useState([]);
  const [modelErrors, setModelErrors] = useState([]);

  const [acEditResponse, setAcEditResponse] = useState({});
  const [account, setAccount] = useState({
    accountNumber: 0,
    balance: 0,
    bankId: 0,
    accountType: 0,
  });

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  useEffect(() => {
    getAccountTypes();
    getAllBanks();
    getAccount(id);
  }, []);

  const getAccount = (id) => {
    console.log("Editing account : ", id);
    if (checkForNumbersOnly(id)) {
      AccountService.getAccount(id)
        .then((response) => {
          console.log(response.data);
          setAccount(response.data);
        })
        .catch((e) => {
          if (e.response.status === 400 || e.response.status === 500) {
            var acEditResponse = {
              responseCode: -1,
              responseMessage: e.response.data,
            };
            setAcEditResponse(acEditResponse);
          } else {
            console.log(e);
          }
        });
    } else navigate("/account");
  };
  const getAccountTypes = () => {
    AccountService.allAccountTypes()
      .then((response) => {
        console.log(response.data);
        setAccountTypes(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const getAllBanks = () => {
    BankService.allBanks()
      .then((response) => {
        console.log(response.data);
        setBanks(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const goBack = (e) => {
    navigate("/account");
  };

  const setField = (field, value) => {
    console.log(field, value);
    setAccount({
      ...account,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };
  const findFormErrors = () => {
    const { accountNumber, accountType, balance, bankId } = account;
    const newErrors = {};

    if (!accountType || accountType === "")
      newErrors.accountType = "Account Type is Required!";
    if (!bankId || bankId === "") newErrors.bankId = "Bank is Required!";

    if (!balance || balance === "") newErrors.balance = "Balance is Required!";
    if (!(!balance || balance === "")) {
      if (!checkForNumbersOnly(balance))
        newErrors.balance = "Only Numbers are Allowed!";
    }

    if (!accountNumber || accountNumber === "")
      newErrors.accountNumber = "Account Number is Required!";
    if (!(!accountNumber || accountNumber === "")) {
      if (!checkForNumbersOnly(accountNumber))
        newErrors.accountNumber = "Only Numbers are Allowed!";
    }
    return newErrors;
  };
  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      if (error.response.data.errors === undefined) {
        console.log("Bad Request!!!");
        errors.push(error.response.data);
      } else {
        for (let prop in error.response.data.errors) {
          if (error.response.data.errors[prop].length > 1) {
            for (let error_ in error.response.data.errors[prop]) {
              errors.push(error.response.data.errors[prop][error_]);
            }
          } else {
            errors.push(error.response.data.errors[prop]);
          }
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setAcEditResponse({});
    setModelErrors([]);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var accountModel = {
        accountNumber: Number(account.accountNumber),
        accountType: Number(account.accountType),
        balance: Number(account.balance),
        bankId: Number(account.bankId),
        accountId: Number(id),
      };

      console.log(accountModel);

      // api call
      AccountService.editAccount(accountModel)
        .then((response) => {
          setModelErrors([]);
          setAcEditResponse({});
          console.log(response.data);

          var acEditResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };
          if (response.data.responseCode === 0) {
            resetForm();
            setAcEditResponse(acEditResponse);

            setTimeout(() => {
              navigate("/account");
            }, 3000);
          } else if (response.data.responseCode === -1) {
            setAcEditResponse(acEditResponse);
          }
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setAcEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);
  const renderOptionsForAccountTypes = () => {
    return accountTypes.map((dt, i) => {
      return (
        <option value={i} key={i} name={dt}>
          {dt}
        </option>
      );
    });
  };
  const renderOptionsForBankList = () => {
    return banks.map((dt, i) => {
      return (
        <option value={dt.bankId} key={i} name={dt.bankName}>
          {dt.bankName}
        </option>
      );
    });
  };
  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-6 mx-auto">
            <div className="card">
              <div className="card-header header">
                <div className="row">
                  <div className="col-md-8 mx-auto">
                    <h3>Edit Account # {id}</h3>
                  </div>
                  <div className="col-md-4 mx-auto">
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => goBack(e)}
                    >
                      <i className="bi bi-arrow-return-left"></i> Back
                    </Button>
                  </div>
                </div>
                <p></p>{" "}
                {acEditResponse && acEditResponse.responseCode === -1 ? (
                  <span className="acEditError">
                    {acEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="acEditSuccess">
                    {acEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="accountNumber">
                        <Form.Label>A/C Number</Form.Label>
                        <Form.Control
                          type="text"
                          value={account.accountNumber}
                          isInvalid={!!errors.accountNumber}
                          onChange={(e) =>
                            setField("accountNumber", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.accountNumber}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="balance">
                        <Form.Label>Balance</Form.Label>
                        <Form.Control
                          className="qtyField"
                          type="text"
                          value={account.balance}
                          isInvalid={!!errors.balance}
                          onChange={(e) => setField("balance", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.balance}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="bankId">
                        <Form.Label>Bank</Form.Label>
                        <Form.Control
                          as="select"
                          value={account.bankId}
                          isInvalid={!!errors.bankId}
                          onChange={(e) => {
                            setField("bankId", e.target.value);
                          }}
                        >
                          <option value="">Select Bank</option>
                          {renderOptionsForBankList()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.bankId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="accountType">
                        <Form.Label>Account Type</Form.Label>
                        <Form.Control
                          as="select"
                          value={account.accountType}
                          isInvalid={!!errors.accountType}
                          onChange={(e) => {
                            setField("accountType", e.target.value);
                          }}
                        >
                          <option value="">Select Account Type</option>
                          {renderOptionsForAccountTypes()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.accountType}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Account
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Account_Edit;

// Angular/src/app/account-edit/account-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import Account from '../models/account';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import Bank from '../models/bank';
import { HttpErrorResponse } from '@angular/common/http';
import AccountType from '../models/accountType';

@Component({
  selector: 'app-account-edit',
  templateUrl: './account-edit.component.html',
  styleUrls: ['./account-edit.component.css']
})
export class AccountEditComponent implements OnInit {
 
  accountTypesName: string[];
  accountTypesCollection: AccountType[];
  
  editingAccount = new Account();

  banks: Array<Bank>;
  accountForm: FormGroup;
  submitted = false;
  accountModel = new Account();

  apiResponse = '';
  responseColor = '';
  errors: string[];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }

  // ok
  ngOnInit(): void {
    this.errors = [];

    this.accountTypesName = [];
    this.accountTypesCollection = [];

    this.loadAccountTypes();

    this.accountForm = this.fb.group({
      BankId: ['', Validators.required],
      AccountNumber: ['', Validators.required],
      Balance: ['', Validators.required],
      AccountType: ['', Validators.required]
    });

    this.loadBanks();
  
    try{
      this.editingAccount = JSON.parse(this.route.snapshot.paramMap.get('selectedAccountObject'));
      this.apiResponse = '';
    }
    catch(Exception){
      this.apiResponse='Invalid Input !';
      this.responseColor = 'red';
      return;
    }   
  
    // do api call to retrieve latest account information 
    this.dataService.getAccount(this.editingAccount.accountId)
      .subscribe(
        data => {
          this.apiResponse = '';
          this.responseColor = 'green';
          this.errors = [];

          // popup form data with incoming api data call  
          this.accountForm.setValue({
            AccountNumber: data.accountNumber,
            Balance: data.balance,
            AccountType: this.convertAccountTypeToFormControl(data.accountType),
            BankId: data.bankId
          });
        },
        error => {
          this.apiResponse = '';
          this.responseColor = 'red';

          this.errors = this.localDataService.display400andEx(error,'Account');       
        });  
  }

  // ok
  loadAccountTypes() {
    this.dataService.getAccountTypes()
      .subscribe(
        data => {
          this.accountTypesName = data;
          this.accountTypesCollection = this.localDataService.getAccountTypeCollection(this.accountTypesName);
        },
        error => {
          console.log(error);
        });
  }
  // ok
  // convert string into int from AccountType[]
  convertAccountType(accountType) {
    var filterByAccountTypeName = this.accountTypesCollection.filter(xx => xx.accountType == accountType);    
    if (filterByAccountTypeName != null) {
      return filterByAccountTypeName[0].indexValue;
    }
    else {
      return -1;
    }
  }
  // ok
  // convert int to string from AccountType[]
  convertAccountTypeToFormControl(acType) {
    var filterByAccountType = this.accountTypesCollection.filter(xx => xx.indexValue == acType);    
    if (filterByAccountType != null) {
      return filterByAccountType[0].accountType;
    }
    else {
      return -1;
    }
  }

  // ok
  public handleError = (controlName: string, errorName: string) => {
    return this.accountForm.controls[controlName].hasError(errorName);
  }

  // ok
  // load bank list
  loadBanks() {
    this.dataService.getBanks()
      .subscribe(
        data => {
          this.banks = data;
        },
        error => {
          console.log(error);
        });
  }

  // ok
  get accountFormControl() {
    return this.accountForm.controls;
  }

  // ok
  resetAccount() {
    this.apiResponse = '';
    this.responseColor = '';
    this.errors = [];
    this.accountForm.reset();
    this.submitted = false;

    this.accountForm.get("AccountType").patchValue('');
    this.accountForm.get("BankId").patchValue('');
  }

  // ok
  numberOnly(event, param): boolean {
    const charCode = (event.which) ? event.which : event.keyCode;

    // 0 = numbers and decimals
    if (param == 0) {
      // numbers and decimals
      if (event.key == '.') {
        return true;
      }
      else {
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
          return false;
        }
        return true;
      }
    }
    else {
      // numbers only
      if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        return false;
      }
      return true;
    }
  }

  // ok
  removeAccount() {
  }

  // ok
  goBack() {
    this.router.navigate(['/account']);
  }

  // ok
  editAccount(): void {
    this.submitted = true;
    if (this.accountForm.valid) {
      this.accountModel.accountNumber = Number(this.accountForm.value["AccountNumber"]);
      this.accountModel.balance = Number(this.accountForm.value["Balance"]);
      this.accountModel.bankId = Number(this.accountForm.value["BankId"]);
      this.accountModel.accountType = this.convertAccountType(this.accountForm.value["AccountType"]);
      this.accountModel.accountId = this.editingAccount.accountId;


      this.dataService.editAccount(this.accountModel)
        .subscribe(
          response => {
            if (response.responseCode == 0) {
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.errors = [];
              this.accountForm.reset();
              this.submitted = false;
              this.accountForm.get("AccountType").patchValue('');
              this.accountForm.get("BankId").patchValue('');

              // redirect to account component
              setTimeout(() => {
                this.router.navigate(['/account']);
              }, 3000);
            }
            else {
              // fail
              // display error message
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
              this.errors = [];
            }
          },
          error => {            
            this.apiResponse = '';
            this.responseColor = 'red';
            this.errors = [];

            this.errors = this.localDataService.display400andEx(error, 'Account');          
          }
        );
    }
  }

}

<div class="container main-container">
    <div>
        <h2>
            Manage Accounts
        </h2>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div [ngStyle]="{'background-color': editingAccount.bgColor}"
                     class="card-header">
                    <h3>
                        <div class="row">
                            <div class="col-md-3 mx-auto">
                                <button type="button" 
                                    (click)="goBack()" 
                                    class="btn btn-primary">
                                    <i class="bi bi-backspace-fill"> Cancel</i>
                                </button>
                            </div>
                            <div *ngIf="!apiResponse && errors.length<1"
                                class="col-md-9 mx-auto edit-account-header">
                                Edit Account [{{editingAccount.accountId}}] here...
                            </div>
                            <div *ngIf="apiResponse" 
                                class="col-md-9 mx-auto edit-account-header">
                                <h4>
                                    <span [style.color]="responseColor">
                                        {{apiResponse}}
                                    </span>
                                    <hr />
                                </h4>                           
                            </div>
                            <div *ngIf="errors.length > 0"
                                class="col-md-9 mx-auto edit-account-header" >
                                <h5>
                                    <ul [style.color]="responseColor">
                                        <li *ngFor="let error of errors">
                                            {{ error }}
                                        </li>
                                    </ul>
                                    <hr />
                                </h5>
                            </div>
                        </div>
                    </h3>
                </div>
            
                <div class="card-body">
                    <form class="form-account" [formGroup]="accountForm">
                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="AccountNumber" class="col-sm-4 col-form-label">
                                    Account Number
                                </label>
                                <div class="col-sm-4">
                                    <input type="text" (keypress)="numberOnly($event,1)" class="form-control"
                                        formControlName="AccountNumber">
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(accountFormControl.AccountNumber.touched || submitted) && accountFormControl.AccountNumber.errors?.required">
                                    Account Number is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="Balance" class="col-sm-4 col-form-label">
                                    Initial Balance
                                </label>
                                <div class="col-sm-4">
                                    <input type="text" (keypress)="numberOnly($event,0)" class="form-control"
                                        formControlName="Balance">
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(accountFormControl.Balance.touched || submitted) && accountFormControl.Balance.errors?.required">
                                    Initial Balance is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="BankId" class="col-sm-4 col-form-label">
                                    Bank
                                </label>
                                <div class="col-sm-4">
                                    <select class="form-control" formControlName="BankId">
                                        <option disabled>Select Bank</option>
                                        <option selected value="">Choose Bank</option>
                                        <option value={{b.bankId}} *ngFor="let b of banks">
                                            {{b.bankName}}
                                        </option>
                                    </select>
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(accountFormControl.BankId.touched || submitted) && handleError('BankId', 'required')">
                                    Bank is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="AccountType" 
                                    class="col-sm-4 col-form-label">
                                    Account Type
                                </label>
                                <div class="col-sm-4">
                                    <select class="form-control" formControlName="AccountType">
                                        <option disabled>Select Account Type</option>
                                        <option value="">Choose Account Type</option>
                                        <option *ngFor="let at of accountTypesName">
                                            {{at}}
                                        </option>
                                    </select>
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(accountFormControl.AccountType.touched || submitted) && handleError('AccountType', 'required')">
                                    Account Type is required!
                                </span>
                            </div>
                        </div>
                    </form>
                </div>

                <div  class="card-footer">
                    <div class="row">
                        <div class="col-sm-3">
                            <button type="button" 
                                (click)="editAccount()" class="btn btn-success">
                                Edit Account
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button type="button" 
                                (click)="resetAccount()" class="btn btn-primary">
                                Reset
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
