// reactapp-pfm/src/components/Bank_Account_List/Bank_Account_List.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import {
  getBankColor,
  getAccountType,
  getAccountColor,
} from "../../services/local.service";
import BankService from "../../services/bank.service";
import AccountService from "../../services/account.service";

import { useNavigate } from "react-router";

import Moment from "moment";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

const Bank_Account_List = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [bankAccounts, setBankAccounts] = useState([]);
  const [bankName, setBankName] = useState("");
  const [bankAcResponse, setBankAcResponse] = useState("");
  const [responseColor, setResponseColor] = useState("");

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const getBankStyle = (_bankName) => {
    var bankColor = getBankColor(_bankName);
    return { backgroundColor: bankColor };
  };

  const getBankAccounts = (id) => {
    console.log("getting accounts for bank : ", id);
    if (checkForNumbersOnly(id)) {
      setBankAcResponse("");
      setResponseColor("");
      AccountService.getBankAccounts(id)
        .then((response) => {
          // console.log(response.data);
          if (response.data.bankName === null) {
            setBankAcResponse("Bank Not Found !");
            setResponseColor("red");
          } else {
            setBankAccounts(response.data.accounts);
            setBankName(response.data.bankName);
          }
        })
        .catch((e) => {
          console.log(e);
        });
    }
  };

  useEffect(() => {
    getBankAccounts(id);
  }, []);

  const displayAcType = (cell, row) => {
    return (
      <div>
        <b>
          <span style={{ color: `${getAccountColor(cell)}` }}>
            {getAccountType(cell)}
          </span>
        </b>
      </div>
    );
  };
  const displayAccountNumber = (cell, row) => {
    return (
      <div>
        <span>
          <i className="bi bi-bag"></i> {cell}
        </span>
      </div>
    );
  };
  const displayActionBtn = (cell, row) => {
    return (
      <div>
        {" "}
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => bankTransactionBeginAdd(e, row)}
        >
          -$ To Payee
        </Button>{" "}
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => bankInputFromSource(e, row)}
        >
          +$ From Source
        </Button>{" "}
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => getAccountStatementAll(e, row)}
        >
          Statement
        </Button>
      </div>
    );
  };
  const bankInputFromSource = (e, account) => {
    var bankTransaction = {
      bankId: id,
      bankName: bankName,
      accountId: account.accountId,
      accountNumber: account.accountNumber,
      balance: account.balance,
    };
    console.log(bankTransaction);

    navigate("/source-to-bank-transaction", {
      state: bankTransaction,
    });
  };
  const bankTransactionBeginAdd = (e, account) => {
    var bankTransaction = {
      bankId: id,
      bankName: bankName,
      accountId: account.accountId,
      accountNumber: account.accountNumber,
      balance: account.balance,
    };
    console.log(bankTransaction);

    navigate("/bank-transaction-add", {
      state: bankTransaction,
    });
  };
  const getAccountStatementAll = (e, account) => {
    var accountVM = {
      bankId: id,
      bankName: bankName,
      accountId: account.accountId,
      // accountId: null,
    };
    console.log(accountVM);

    navigate("/account-statement-all", {
      state: accountVM,
    });
  };

  const columns = [
    {
      dataField: "accountNumber",
      text: "Account Number",
      sort: true,
      formatter: (cell, row) => displayAccountNumber(cell, row),
    },
    {
      dataField: "accountType",
      text: "Account Type",
      sort: true,
      formatter: (cell, row) => displayAcType(cell, row),
    },
    {
      dataField: "balance",
      text: "Balance",
    },
    {
      dataField: "actions",
      text: "Actions",
      formatter: (cell, row) => displayActionBtn(cell, row),
    },
  ];

  const goBack = (e) => {
    navigate("/bank");
  };

  return (
    <div className="container">
      <div className="mainHeader">Bank-Accounts</div>
      <hr />
      <div className="row">
        <div className="col-md-1 mx-auto"></div>
        <div className="col-md-10 mx-auto">
          <div className="card">
            <div style={getBankStyle(bankName)} className="card-header">
              <div className="row">
                <div className="col-md-10 mx-auto">
                  {bankAcResponse ? (
                    <h4 style={{ color: responseColor }}>{bankAcResponse}</h4>
                  ) : (
                    <h4>{bankName} Accounts here...</h4>
                  )}
                </div>
                <div className="col-md-2 mx-auto">
                  <Button
                    className="btn btn-primary"
                    type="button"
                    onClick={(e) => goBack(e)}
                  >
                    <i className="bi bi-arrow-return-left"></i> Back
                  </Button>
                </div>
              </div>
            </div>
          </div>

          <p></p>
          {bankAccounts && bankAccounts.length > 0 ? (
            <BootstrapTable
              bootstrap4
              keyField="accountId"
              data={bankAccounts}
              columns={columns}
              pagination={paginationFactory({ sizePerPage: 5 })}
              filter={filterFactory()}
            />
          ) : (
            <div className="noBanks">No Accounts!</div>
          )}
        </div>
        <div className="col-md-1 mx-auto"></div>
      </div>
    </div>
  );
};

export default Bank_Account_List;

// Angular/src/app/bank-account-list/bank-account-list.component.ts
import { Component, OnInit, ɵɵtrustConstantResourceUrl } from '@angular/core';
import { DataService } from '../services/data.service';
import Bank from '../models/bank';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import Account from '../models/account';
import { ActivatedRoute, Router } from '@angular/router';
import BankAccountVM from '../models/bankAccountVM';
import BankTransaction from '../models/bankTransaction';
import AccountType from '../models/accountType';
import AccountVM from '../models/accountVM';
import Transaction from '../models/transaction';
import AccountStatement from '../models/accountStatement';
import PayeeType from '../models/payeeType';
import { DatePipe } from '@angular/common'

@Component({
  selector: 'app-bank-account-list',
  templateUrl: './bank-account-list.component.html',
  styleUrls: ['./bank-account-list.component.css']
})
export class BankAccountListComponent implements OnInit {

  isDataAvailable: boolean = false;

  accountStatement: AccountStatement;
  transactions: Transaction[];

  accountTypesName: string[];
  accountTypesCollection: AccountType[];

  payeeTypesName: string[];
  payeeTypesCollection: PayeeType[];

  bankTransaction: BankTransaction;

  bankAccounts: BankAccountVM;

  bankColor = '';
  accountColor = '';

  apiResponse = '';
  responseColor = '';
  errors: string[];

  constructor(public datepipe: DatePipe, public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }

  // ok
  ngOnInit() {
    this.accountStatement = new AccountStatement();
    this.transactions = [];
    this.accountStatement.transactions = this.transactions;

    this.errors = [];
    this.bankColor = '';
    this.accountColor = '';

    this.accountTypesName = [];
    this.accountTypesCollection = [];

    this.payeeTypesName = [];
    this.payeeTypesCollection = [];

    this.bankTransaction = new BankTransaction();

    this.bankAccounts = new BankAccountVM();

    this.bankAccounts.bankId = Number(this.route.snapshot.paramMap.get('id'));

    if (isNaN(+this.bankAccounts.bankId)) {
      console.log('Not a Number!');
      this.router.navigate(['/bank']);
    }
    else {
      this.loadPayeeTypes();
      this.loadAccountTypes();

      // prepare for bank-transaction-begin-add process
      this.bankTransaction.bankId = this.bankAccounts.bankId;

      // do api call to retrieve latest bank's account information 
      this.dataService.getBankAccounts(this.bankAccounts.bankId)
        .subscribe(
          data => {
            console.log(data);
            this.apiResponse = '';
            this.responseColor = 'green';
            this.errors = [];

            this.bankAccounts = data;
            if (data.bankName != null) {
              this.bankColor = this.localDataService.getBankColor(this.bankAccounts.bankName);

              // accounts sort by accountType
              this.bankAccounts.accounts.sort((a, b) => String(a.accountType).localeCompare((String)(b.accountType)));
            }
            else {
              this.apiResponse = 'Bank Not Found !';
              this.responseColor = 'red';
              this.errors = [];
            }
          },
          error => {
            this.apiResponse = '';
            this.responseColor = 'red';
            this.errors = [];
          });
    }
  }

  // ok
  loadAccountTypes() {
    this.dataService.getAccountTypes()
      .subscribe(
        data => {
          this.accountTypesName = data;
          this.accountTypesCollection = this.localDataService.getAccountTypeCollection(this.accountTypesName);

          this.isDataAvailable = true;
        },
        error => {
          console.log(error);
        });
  }
  // ok
  // convert int to string from AccountType[]
  displayAccountType(acType) {
    var filterByAccountType = this.accountTypesCollection.filter(xx => xx.indexValue == acType);
    if (filterByAccountType != null) {
      return filterByAccountType[0].accountType;
    }
    else {
      return -1;
    }
  }

  // ok
  loadPayeeTypes() {
    this.dataService.getPayeeTypes()
      .subscribe(
        data => {
          this.payeeTypesName = data;
          this.payeeTypesCollection = this.localDataService.getPayeeTypeCollection(this.payeeTypesName);
        },
        error => {
          console.log(error);
        });
  }
  // ok
  displayPayeeType(payeeType) {
    if (this.payeeTypesCollection != null) {
      return this.payeeTypesCollection[payeeType].payeeType;
    }
    else {
      return 0;
    }
  }

  // ok
  goBack() {
    this.router.navigate(['/bank']);
  }

  // ok
  prepareBankTransactionObject(account){
    this.bankTransaction.accountId = account.accountId;
    this.bankTransaction.accountNumber = account.accountNumber;
    this.bankTransaction.bankColor = this.bankColor;
    this.bankTransaction.accountColor = this.localDataService.getAccountTypeColor(account.accountType);
    this.bankTransaction.bankName = this.bankAccounts.bankName;
    this.bankTransaction.balance = account.balance;

    // store this bankTransaction to local-data-service
    this.localDataService.setBankTransaction(this.bankTransaction);
  }
  // ok
  bankTransactionBeginAdd(account) {
    this.prepareBankTransactionObject(account);

    // redirect to bank-transaction-add 
    this.router.navigate(['/bank-transaction-add']);
  }

  // ok
  getAccountStatementAll(account) {    
    var accountVM = new AccountVM();
    accountVM.accountId = account.accountId;

    this.dataService.getAccountStatementAll(accountVM)
      .subscribe(
        response => {

          console.log(response);

          if (response.accountId) {
            // success       
            this.apiResponse = '';
            this.responseColor = 'green';
            this.errors = [];

            // popup display name for account-type
            // popup display name for payee-type
            this.accountStatement = response;
            this.accountStatement.accountTypeDisplay = (String)(this.displayAccountType(this.accountStatement.accountType));
            this.accountStatement.transactions.forEach((element) => {
              element.payeeTypeDisplay = (String)(this.displayPayeeType(element.payeeType));
              element.transactionTypeDisplay = this.localDataService.getTransactionType(element.transactionType);
            });
            // store accountStatement @ local-data-service & redirect
            // to account-statement-all component
            this.localDataService.setAccountStatement(response);

            setTimeout(() => {
              this.router.navigate(['/account-statement-all']);
            }, 2000);
          }
          else if (response.responseCode == -1) {
            // server error
            // server exception
            this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
            this.responseColor = 'red';
            this.errors = [];
          }
        },
        error => {
          this.apiResponse = '';
          this.responseColor = 'red';
          this.errors = [];
          this.errors = this.localDataService.display400andEx(error, 'Account-Statement');
        }
      );
  }

  // ok
  bankInputFromSource(account){
    this.prepareBankTransactionObject(account);

    // redirect to source-bank-transaction
    this.router.navigate(['/source-bank-transaction']);
  }
}

<div class="container main-container">
    <div>
        <h2>
            Manage Bank / Accounts
        </h2>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">
                <div class="card-header" 
                    [ngStyle]="{'background-color': bankColor}">                               
                    <h3 >
                        <div class="row">
                            <div class="col-md-4 mx-auto">
                                <button type="button" 
                                    (click)="goBack()" 
                                    class="btn btn-primary">
                                    <i class="bi bi-backspace-fill"> Cancel</i>
                                </button>
                            </div>
                            <div class="col-md-8 mx-auto edit-bank-header">
                                {{bankAccounts.bankName}} Accounts here...
                            </div>
                        </div>
                    </h3>
                    <h4 *ngIf="apiResponse">
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                        <hr />
                    </h4>
                    <h5 *ngIf="errors.length > 0">
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of errors">
                                {{ error }}
                            </li>
                        </ul>
                        <hr />
                    </h5>
                </div>
                <div *ngIf="(bankAccounts.accounts?.length > 0 && isDataAvailable)"
                    class="card-body">
                    <table class="table table-text ">
                        <thead class="table-header-text">
                            <tr>
                                <th>A/C Number</th>
                                <th>Type</th>
                                <th>Balance</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr *ngFor="let a of bankAccounts.accounts">
                                <td>
                                    <h2><i class="bi bi-bag">{{a.accountNumber}}</i></h2>
                                </td>
                                <td [style.color]="localDataService.getAccountTypeColor(a.accountType)">
                                    {{displayAccountType(a.accountType)}}
                                </td>                                            
                                <td>{{a.balance}}</td>   
                                <td>
                                    <div class="row">
                                        <div class="col-4">
                                            <button type="button" 
                                                (click)="bankTransactionBeginAdd(a)" 
                                                class="btn btn-primary">
                                               -$  To  Payee
                                            </button>
                                        </div>   
                                        <div class="col-5">
                                            <button type="button"
                                                (click)="bankInputFromSource(a)" 
                                                    class="btn btn-primary">
                                                +$ From Source
                                            </button>
                                        </div>
                                        <div class="col-3">
                                            <button type="button" (click)="getAccountStatementAll(a)" class="btn btn-primary">
                                                Statement
                                            </button>
                                        </div>
                                    </div>
                                </td>                            
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div *ngIf="!apiResponse && !(bankAccounts.accounts?.length > 0)" 
                    class="card-body no-bank-account">
                    No Accounts Yet !!!
                </div>
            </div>
        </div>
    </div>
</div>
