// reactapp-pfm/src/components/Bank_Transaction_Add/Bank_Transaction_Add.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import { getBankColor } from "../../services/local.service";
import BankTransactionService from "../../services/bank.transaction.service";

import { useNavigate, useLocation } from "react-router";

import Moment from "moment";

const Bank_Tranaction_Add = () => {
  let navigate = useNavigate();

  const { state } = useLocation();
  const { bankId, bankName, accountId, accountNumber, balance } = state || {}; // Read values passed on state

  const [payees, setPayees] = useState([]);
  const [modelErrors, setModelErrors] = useState([]);
  const [bankTrAddCreateResponse, setBankTrAddCreateResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  // reset form
  // form reference
  const formRef = useRef(null);

  useEffect(() => {
    if (accountId === undefined || balance === undefined)
      navigate("/bank-account-list" + bankId);

    listOfPayees();
  }, []);

  const listOfPayees = () => {
    BankTransactionService.listOfPayees()
      .then((response) => {
        setPayees(response.data);
        console.log(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const getBankStyle = (_bankName) => {
    var bankColor = getBankColor(_bankName);
    return { backgroundColor: bankColor };
  };
  const goBack = (e) => {
    navigate("/bank-account-list/" + bankId);
  };

  const setField = (field, value) => {
    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const { payeeId, transactionAmount, transactionDate } = form;
    const newErrors = {};

    if (!payeeId || payeeId === "") newErrors.payeeId = "Payee is Required!";
    if (!transactionDate || transactionDate === "")
      newErrors.transactionDate = "Transaction Date is Required!";

    if (!transactionAmount || transactionAmount === "")
      newErrors.transactionAmount = "Transaction Amount is Required!";

    if (!(!transactionAmount || transactionAmount === "")) {
      if (!checkForNumbersOnly(transactionAmount))
        newErrors.transactionAmount = "Only Numbers are Allowed!";
    }
    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };
  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var bankTransaction = {
        payeeId: form.payeeId,
        transactionAmount: Number(form.transactionAmount),
        transactionDate: form.transactionDate,
        bankId: bankId,
        accountId: accountId,
        balance: balance,
      };

      console.log(bankTransaction);

      // api call
      BankTransactionService.addBankTransaction(bankTransaction)
        .then((response) => {
          setModelErrors([]);
          setBankTrAddCreateResponse({});
          console.log(response.data);

          var trCreateResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };
          if (response.data.responseCode === 0) {
            resetForm();
            setBankTrAddCreateResponse(trCreateResponse);

            setTimeout(() => {
              navigate("/bank-account-list/" + bankId);
            }, 3000);
          } else if (response.data.responseCode === -1) {
            setBankTrAddCreateResponse(trCreateResponse);
          }
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setBankTrAddCreateResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setBankTrAddCreateResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  const renderOptionsForPayees = () => {
    return payees.map((dt, i) => {
      return (
        <option value={dt.payeeId} key={i} name={dt.payeeName}>
          {dt.payeeName}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-8 mx-auto">
            <div className="card">
              <div style={getBankStyle(bankName)} className="card-header">
                <div className="row">
                  <div className="col-md-10 mx-auto">
                    <h3>Add Your Transaction Here...</h3>
                    <div className="bankHeader">
                      Bank : {bankName}
                      <br />
                      Account Number : {accountNumber}
                      <br />
                      Maximum Pay : {balance}
                    </div>
                  </div>
                  <div className="col-md-2 mx-auto">
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => goBack(e)}
                    >
                      <i className="bi bi-arrow-return-left"></i> Back
                    </Button>
                  </div>
                </div>
                <p></p>
                {bankTrAddCreateResponse &&
                bankTrAddCreateResponse.responseCode === -1 ? (
                  <span className="bankTrAddCreateError">
                    {bankTrAddCreateResponse.responseMessage}
                  </span>
                ) : (
                  <span className="bankTrAddCreateSuccess">
                    {bankTrAddCreateResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="payeeId">
                        <Form.Label>Payees</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.payeeId}
                          onChange={(e) => {
                            setField("payeeId", e.target.value);
                          }}
                        >
                          <option value="">Select Payee</option>
                          {renderOptionsForPayees()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.payeeId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <Form.Group controlId="transactionAmount">
                        <Form.Label>Amount</Form.Label>
                        <Form.Control
                          className="qtyField"
                          type="text"
                          isInvalid={!!errors.transactionAmount}
                          onChange={(e) =>
                            setField("transactionAmount", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.transactionAmount}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Label>Transaction Date</Form.Label>
                      <Form.Control
                        type="date"
                        name="transactionDate"
                        placeholder="Transaction Date"
                        isInvalid={!!errors.transactionDate}
                        onChange={(e) =>
                          setField("transactionDate", e.target.value)
                        }
                      />
                      <Form.Control.Feedback type="invalid">
                        {errors.transactionDate}
                      </Form.Control.Feedback>
                    </div>
                  </div>
                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Commit Transaction
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Cancel
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Bank_Tranaction_Add;

// Angular/src/app/bank-transaction-add/bank-transaction-add.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import { ActivatedRoute, Router } from '@angular/router';
import BankTransaction from '../models/bankTransaction';
import PayeeType from '../models/payeeType';
import Payee from '../models/payee';


@Component({
  selector: 'app-bank-transaction-add',
  templateUrl: './bank-transaction-add.component.html',
  styleUrls: ['./bank-transaction-add.component.css']
})
export class BankTransactionAddComponent implements OnInit {

  bankTransaction: BankTransaction;
  payees: Payee[];

  transactionForm: FormGroup;
  submitted = false;

  bankColor = '';
  accountColor = '';
  apiResponse = '';
  responseColor = '';
  errors: string[];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }

  // retrieve this stored bankTransaction from local-data-service
  // @ bank-transaction-add component init()
  // if null then return back to bank component
  // else store it @ bank-transaction-add component & display 
  // form to input other values for bankTransaction
  // & finally send to data-service for api call
  ngOnInit(): void {
    this.bankTransaction = new BankTransaction();
    this.bankTransaction = this.localDataService.getBankTransaction();
    console.log(this.bankTransaction);

    if (!this.bankTransaction.bankId) {
      this.router.navigate(['/bank']);
    }

    this.bankColor = this.bankTransaction.bankColor;
    this.accountColor = this.bankTransaction.accountColor;

    this.errors = [];
    this.payees = [];

    this.loadPayees();

    this.transactionForm = this.fb.group({
      PayeeId: ['', Validators.required],
      TransactionAmount: ['', Validators.required],
      TransactionDate: ['', Validators.required]
    });
  }

  // ok
  loadPayees() {
    this.dataService.listOfPayees()
      .subscribe(
        data => {
          this.payees = data;
        },
        error => {
          console.log(error);
        });
  }

  resetBankTransaction() {
    this.apiResponse = '';
    this.transactionForm.reset();
    this.transactionForm.get("PayeeId").patchValue('');
    this.submitted = false;
    this.errors = [];
    this.responseColor = '';

    // to prevent back history
    this.bankTransaction = new BankTransaction();
    this.localDataService.setBankTransaction(this.bankTransaction);
  }

  addBankTransaction() {
    this.submitted = true;
    if (this.transactionForm.valid) {
      this.bankTransaction.payeeId = Number(this.transactionForm.value["PayeeId"]);
      this.bankTransaction.transactionAmount = Number(this.transactionForm.value["TransactionAmount"]);
      this.bankTransaction.transactionDate = new Date(this.transactionForm.value["TransactionDate"].year + '/' + this.transactionForm.value["TransactionDate"].month + '/' + this.transactionForm.value["TransactionDate"].day);

      console.log(this.bankTransaction);

      this.dataService.addBankTransaction(this.bankTransaction)
        .subscribe(
          response => {

            console.log(response);

            if (response.responseCode == 0) {
              // success    
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.errors = [];

              this.transactionForm.reset();
              this.transactionForm.get("PayeeId").patchValue('');
              this.submitted = false;

              setTimeout(() => {
                this.router.navigate(['/bank']);
                this.apiResponse = '';
              }, 3000);
            }
            else {
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';

              this.errors = [];
            }
            // to prevent back history
            this.bankTransaction = new BankTransaction();
            this.localDataService.setBankTransaction(this.bankTransaction);
          },
          error => {
            this.apiResponse = '';
            this.responseColor = 'red';
            this.errors = [];

            // to prevent back history
            this.bankTransaction = new BankTransaction();
            this.localDataService.setBankTransaction(this.bankTransaction);

            this.errors = this.localDataService.display400andEx(error, 'Bank-Transaction');
          }
        );
    }
  }

  // ok
  public handleError = (controlName: string, errorName: string) => {
    return this.transactionForm.controls[controlName].hasError(errorName);
  }

  // ok
  get transactionFormControl() {
    return this.transactionForm.controls;
  }

  // ok
  goBack() {
    // to prevent back history
    this.bankTransaction = new BankTransaction();
    this.localDataService.setBankTransaction(this.bankTransaction);

    this.router.navigate(['/bank']);
  }

  // ok
  // disable browser history
  ngOnDestroy() {
    this.bankTransaction = new BankTransaction();
    this.localDataService.setBankTransaction(this.bankTransaction);
  }
}
<div class="container main-container">
    <div>
        <h2>
            Manage Bank / Account / Transaction
        </h2>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header" 
                    [ngStyle]="{'background-color': bankColor}">
                    <h3>
                        <div class="row">
                            <div class="col-md-4 mx-auto">
                                <button type="button" 
                                    (click)="goBack()" 
                                    class="btn btn-primary">
                                    <i class="bi bi-backspace-fill"> Cancel</i>
                                </button>
                            </div>
                            <div class="col-md-8 mx-auto add-bank-transaction-header">
                                Add Your Transaction here...
                            </div>
                        </div>
                    </h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <h6 class="maximumPay" 
                                *ngIf="bankTransaction.bankId">
                                <span>
                                    Bank : {{bankTransaction.bankName}}
                                    <p></p>
                                    A/C Number : {{bankTransaction.accountNumber}}
                                    <p></p>
                                    Maximum Pay : {{bankTransaction.balance}}
                                </span>
                            </h6>
                        </div>
                    </div>
                    <h4 *ngIf="apiResponse">
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                        <hr />
                    </h4>
                    <h5 *ngIf="errors.length > 0">
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of errors">
                                {{ error }}
                            </li>
                        </ul>
                        <hr />
                    </h5>

                </div>
                <div class="card-body">
                    <form class="form-payee" 
                        [formGroup]="transactionForm">
                        <div class="form-group">
                            <div class="row mb-2">
                                <label for="PayeeId" 
                                    [ngStyle]="{'color': accountColor}"
                                    class="col-sm-2 col-form-label">
                                    Payee
                                </label>
                                <div class="col-sm-5">
                                    <select class="form-control" 
                                        formControlName="PayeeId">
                                        <option disabled>Select Payee</option>
                                        <option value="">Choose Payee</option>
                                        <option value="{{p.payeeId}}" 
                                            *ngFor="let p of payees">
                                            {{p.payeeName}}
                                        </option>
                                    </select>
                                </div>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.PayeeId.touched || submitted) && handleError('PayeeId', 'required')">
                                    Payee is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="TransactionAmount" 
                                    [ngStyle]="{'color': accountColor}"
                                    class="col-sm-2 col-form-label">
                                    Amount
                                </label>
                                <div class="col-sm-5">
                                    <input type="text" 
                                        class="form-control" 
                                        formControlName="TransactionAmount">
                                </div>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.TransactionAmount.touched || submitted) && transactionFormControl.TransactionAmount.errors?.required">
                                    Transaction Amount is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group datepicker">
                            <div class="row mb-3">
                                <label 
                                    for="TransactionDate" 
                                    [ngStyle]="{'color': accountColor}"
                                    class="col-sm-2 col-form-label">Date</label>
                                <div class="col-sm-5" >
                                    <div class="row">
                                        <div class="col-sm-8">
                                            <input class="form-control" placeholder="yyyy-mm-dd" name="dp" formControlName="TransactionDate" ngbDatepicker
                                                #d="ngbDatepicker">
                                            </div>
                                        <div class="col-sm-4">
                                            <span class="input-group-append">
                                                <button class="btn btn-outline-secondary calendar" (click)="d.toggle()" type="button">
                                                    <i class="bi bi-calendar-check-fill"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.TransactionDate.touched || submitted) && transactionFormControl.TransactionDate.errors?.required">
                                    Transaction Date is required!
                                </span>
                                <span class="col-sm-5 text-danger"
                                    *ngIf="(transactionFormControl.TransactionDate.touched || submitted) && !transactionFormControl.TransactionDate.valid && !transactionFormControl.TransactionDate.errors?.required ">
                                    Invalid Transaction Date !
                                </span>
                            </div>  
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-4">
                            <button type="button" 
                                (click)="addBankTransaction()" 
                                class="btn btn-success">
                                Commit Transaction
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button type="button" 
                                (click)="resetBankTransaction()" 
                                class="btn btn-primary">
                                Reset
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
