// Angular/src/app/payee-edit/payee-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import Payee from '../models/payee';
import PayeeType from '../models/payeeType';
import { HttpErrorResponse } from '@angular/common/http';
import AccountType from '../models/accountType';

@Component({
  selector: 'app-payee-edit',
  templateUrl: './payee-edit.component.html',
  styleUrls: ['./payee-edit.component.css']
})
export class PayeeEditComponent implements OnInit {
  payeeTypesName: string[];
  payeeTypesCollection: PayeeType[];
  
  editingPayee = new Payee();

  payeeForm: FormGroup;
  submitted = false;
  payeeModel = new Payee();

  apiResponse = '';
  responseColor = '';
  errors: string[];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }


  ngOnInit(): void {
    this.errors = [];

    this.payeeTypesName = [];
    this.payeeTypesCollection = [];

    this.loadPayeeTypes();

    this.payeeForm = this.fb.group({
      PayeeName: ['', Validators.required],
      Description: ['', Validators.required],
      PayeeACNumber: ['', Validators.required],
      Balance: ['', Validators.required],
      PayeeType: ['', Validators.required]
    });
  
    try{
      this.editingPayee = JSON.parse(this.route.snapshot.paramMap.get('selectedPayeeObject'));
      this.apiResponse = '';
    }
    catch(Exception){
      this.apiResponse='Invalid Input !';
      this.responseColor = 'red';
      return;
    }   
  
    // do api call to retrieve latest account information 
    this.dataService.getPayee(this.editingPayee.payeeId)
      .subscribe(
        data => {
          this.apiResponse = '';
          this.responseColor = 'green';
          this.errors = [];

          // popup form data with incoming api data call  
          this.payeeForm.setValue({
            PayeeACNumber: data.payeeACNumber,
            Balance: data.balance,
            PayeeType: this.convertPayeeTypeToFormControl(data.payeeType),
            PayeeName: data.payeeName,
            Description: data.description
          });
        },
        error => {
          this.apiResponse = '';
          this.responseColor = 'red';

          if (error.status === 500) {
            this.apiResponse = error.error;
          }
          else if (error.status === 400) {
            this.errors = this.localDataService.display400andEx(error, 'Payee');            
            // this.errors = this.localDataService.displayModelStateErrors(error, 'Payee');
          }
          else
            console.log(error);           
          
        });  
  }

  loadPayeeTypes() {
    this.dataService.getPayeeTypes()
      .subscribe(
        data => {
          this.payeeTypesName = data;
          this.payeeTypesCollection = this.localDataService.getPayeeTypeCollection(this.payeeTypesName);
        },
        error => {
          console.log(error);
        });
  }
  // convert string into int from PayeeType[]
  convertPayeeType(payeeType) {
    var filterByPayeeTypeName = this.payeeTypesCollection.filter(xx => xx.payeeType == payeeType);    
    if (filterByPayeeTypeName != null) {
      return filterByPayeeTypeName[0].indexValue;
    }
    else {
      return -1;
    }
  }
  // convert int to string from payeeType[]
  convertPayeeTypeToFormControl(payeeType) {
    var filterByPayeeType = this.payeeTypesCollection.filter(xx => xx.indexValue == payeeType);    
    if (filterByPayeeType != null) {
      return filterByPayeeType[0].payeeType;
    }
    else {
      return -1;
    }
  }

  public handleError = (controlName: string, errorName: string) => {
    return this.payeeForm.controls[controlName].hasError(errorName);
  }
  get payeeFormControl() {
    return this.payeeForm.controls;
  }

  resetPayee() {
    this.apiResponse = '';
    this.responseColor = '';
    this.errors = [];
    this.payeeForm.reset();
    this.submitted = false;

    this.payeeForm.get("PayeeType").patchValue('');
  }

  numberOnly(event, param): boolean {
    const charCode = (event.which) ? event.which : event.keyCode;

    // 0 = numbers and decimals
    if (param == 0) {
      // numbers and decimals
      if (event.key == '.') {
        return true;
      }
      else {
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
          return false;
        }
        return true;
      }
    }
    else {
      // numbers only
      if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        return false;
      }
      return true;
    }
  }
    goBack() {
    this.router.navigate(['/payee']);
  }

  editPayee(): void {
    this.submitted = true;
    if (this.payeeForm.valid) {
      this.payeeModel.payeeACNumber = this.payeeForm.value["PayeeACNumber"];
      this.payeeModel.balance = this.convertPayeeType(this.payeeForm.value["PayeeType"])===3 ? Number(this.payeeForm.value["Balance"]) : 0;
      this.payeeModel.payeeName = this.payeeForm.value["PayeeName"];
      this.payeeModel.description = this.payeeForm.value["Description"];
      this.payeeModel.payeeType = this.convertPayeeType(this.payeeForm.value["PayeeType"]);
      this.payeeModel.payeeId = this.editingPayee.payeeId;


      this.dataService.editPayee(this.payeeModel)
        .subscribe(
          response => {
            if (response.responseCode == 0) {
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.errors = [];
              this.payeeForm.reset();
              this.submitted = false;
              this.payeeForm.get("PayeeType").patchValue('');

              // redirect to payee component
              setTimeout(() => {
                this.router.navigate(['/payee']);
              }, 3000);
            }
            else {
              // fail
              // display error message
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
              this.errors = [];
            }
          },
          error => {            
            this.apiResponse = '';
            this.responseColor = 'red';
            this.errors = [];

            // this.errors = this.localDataService.display400andEx(error, 'Payee');                  
            if (error.status === 400) {            
              this.errors = this.localDataService.displayModelStateErrors(error, 'Payee');
            }
            else
              console.log(error);
            }
        );
    }
  }
}

<div class="container main-container">
    <div>
        <h2>
            Manage Payees
        </h2>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div                     
                    class="card-header">
                    <h3>
                        <div class="row">
                            <div class="col-md-3 mx-auto">
                                <button type="button" 
                                    (click)="goBack()" 
                                    class="btn btn-primary">
                                    <i class="bi bi-backspace-fill"> Cancel</i>
                                </button>
                            </div>
                            <div *ngIf="!apiResponse && errors.length<1" 
                                class="col-md-9 mx-auto edit-payee-header">
                                Edit Payee [{{editingPayee.payeeId}}] here...
                            </div>
                            <div *ngIf="apiResponse" 
                                class="col-md-9 mx-auto edit-payee-header">
                                <h4>
                                    <span [style.color]="responseColor">
                                        {{apiResponse}}
                                    </span>
                                    <hr />
                                </h4>
                            </div>
                            <div *ngIf="errors.length > 0" 
                                    class="col-md-9 mx-auto edit-payee-header">
                                <h5>
                                    <ul [style.color]="responseColor">
                                        <li *ngFor="let error of errors">
                                            {{ error }}
                                        </li>
                                    </ul>
                                    <hr />
                                </h5>
                            </div>
                        </div>
                    </h3>
                </div>

                <div class="card-body">
                    <form class="form-payee" 
                        [formGroup]="payeeForm">
                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="PayeeACNumber" 
                                    class="col-sm-4 col-form-label">
                                    Payee A/C Number
                                </label>
                                <div class="col-sm-4">
                                    <input type="text" 
                                        class="form-control"
                                        formControlName="PayeeACNumber">
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(payeeFormControl.PayeeACNumber.touched || submitted) && payeeFormControl.PayeeACNumber.errors?.required">
                                    A/C Number is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="Balance" 
                                    class="col-sm-4 col-form-label">
                                    Balance
                                </label>
                                <div class="col-sm-4">
                                    <input type="text" 
                                        (keypress)="numberOnly($event,0)" 
                                        class="form-control"
                                        formControlName="Balance">
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(payeeFormControl.Balance.touched || submitted) && payeeFormControl.Balance.errors?.required">
                                    Balance is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="PayeeName" 
                                    class="col-sm-4 col-form-label">
                                    Payee Name
                                </label>
                                <div class="col-sm-4">
                                    <input type="text" 
                                        class="form-control" 
                                        formControlName="PayeeName">
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(payeeFormControl.PayeeName.touched || submitted) && payeeFormControl.PayeeName.errors?.required">
                                    Payee Name is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="Description" 
                                    class="col-sm-4 col-form-label">
                                    Description
                                </label>
                                <div class="col-sm-4">
                                    <input type="text" 
                                        class="form-control" 
                                        formControlName="Description">
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(payeeFormControl.Description.touched || submitted) && payeeFormControl.Description.errors?.required">
                                    Description is required!
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row mb-3">
                                <label for="PayeeType" 
                                    class="col-sm-4 col-form-label">
                                    Payee Type
                                </label>
                                <div class="col-sm-4">
                                    <select class="form-control" 
                                        formControlName="PayeeType">
                                        <option disabled>Select Payee Type</option>
                                        <option value="">Choose Payee Type</option>
                                        <option *ngFor="let at of payeeTypesName">
                                            {{at}}
                                        </option>
                                    </select>
                                </div>
                                <span class="col-sm-4 text-danger"
                                    *ngIf="(payeeFormControl.PayeeType.touched || submitted) && handleError('PayeeType', 'required')">
                                    Payee Type is required!
                                </span>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-3">
                            <button type="button" 
                                (click)="editPayee()" 
                                class="btn btn-success">
                                Edit Payee
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button type="button" 
                                (click)="resetPayee()" 
                                class="btn btn-primary">
                                Reset
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-pfm/src/components/Payee_Edit/Payee_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import { getBankColor } from "../../services/local.service";
import PayeeService from "../../services/payee.service";

import { useNavigate } from "react-router";

import Moment from "moment";

const Payee_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [payeeTypes, setPayeeTypes] = useState([]);
  const [modelErrors, setModelErrors] = useState([]);

  const [payeeEditResponse, setPayeeEditResponse] = useState({});
  const [payee, setPayee] = useState({
    payeeName: "",
    description: "",
    payeeACNumber: "",
    payeeType: 0,
    balance: 0,
  });

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  const [showBalance, setShowBalance] = useState(false);

  useEffect(() => {
    getPayeeTypes();
    getPayee(id);
  }, []);

  const getPayee = (id) => {
    console.log("Editing payee : ", id);
    if (checkForNumbersOnly(id)) {
      PayeeService.getPayee(id)
        .then((response) => {
          console.log(response.data);
          setPayee(response.data);
          if (response.data.payeeType === 3) setShowBalance(true);
          else setShowBalance(false);
        })
        .catch((e) => {
          if (e.response.status === 400 || e.response.status === 500) {
            var payeeEditResponse = {
              responseCode: -1,
              responseMessage: e.response.data,
            };
            setPayeeEditResponse(payeeEditResponse);
          } else {
            console.log(e);
          }
        });
    } else navigate("/payee");
  };
  const getPayeeTypes = () => {
    PayeeService.allPayeeTypes()
      .then((response) => {
        console.log(response.data);
        setPayeeTypes(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const goBack = (e) => {
    navigate("/payee");
  };

  const setField = (field, value) => {
    if (field === "payeeType" && value === "3") setShowBalance(true);
    else if (field === "payeeType" && value !== "3") setShowBalance(false);

    setPayee({
      ...payee,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };
  const findFormErrors = () => {
    const { payeeACNumber, description, payeeType, balance, payeeName } = payee;
    const newErrors = {};

    if (!payeeType || payeeType === "")
      newErrors.payeeType = "Payee Type is Required!";

    if (!payeeACNumber || payeeACNumber === "")
      newErrors.payeeACNumber = "Payee A/C Number is Required!";

    if (!payeeName || payeeName === "")
      newErrors.payeeName = "Payee Name is Required!";

    if (showBalance) {
      if (!balance || balance === "")
        newErrors.balance = "Balance is Required!";
    }
    if (!(!balance || balance === "")) {
      if (!checkForNumbersOnly(balance))
        newErrors.balance = "Only Numbers are Allowed!";
    }

    if (!description || description === "")
      newErrors.description = "Description is Required!";

    return newErrors;
  };
  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      if (error.response.data.status === 400) {
        console.log("Bad Request!!!");
        errors.push(error.response.data.title + "!");
      } else {
        for (let prop in error.response.data) {
          if (error.response.data[prop].length > 1) {
            for (let error_ in error.response.data[prop]) {
              errors.push(error.response.data[prop][error_]);
            }
          } else {
            errors.push(error.response.data[prop]);
          }
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setPayee({
      ...payee,
      payeeName: "",
      description: "",
      payeeACNumber: "",
      payeeType: 0,
      balance: 0,
    });
    setPayeeEditResponse({});
    setModelErrors([]);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var payeeModel = {
        payeeName: payee.payeeName,
        description: payee.description,
        payeeACNumber: payee.payeeACNumber,
        payeeType: Number(payee.payeeType),
        balance: showBalance ? Number(payee.balance) : 0,
        payeeId: Number(id),
      };

      console.log(payeeModel);

      // api call
      PayeeService.editPayee(payeeModel)
        .then((response) => {
          setModelErrors([]);
          setPayeeEditResponse({});
          console.log(response.data);

          var editResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };
          if (response.data.responseCode === 0) {
            resetForm();
            setPayeeEditResponse(editResponse);

            setTimeout(() => {
              navigate("/payee");
            }, 3000);
          } else if (response.data.responseCode === -1) {
            setPayeeEditResponse(editResponse);
          }
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setPayeeEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);
  const renderOptionsForPayeeTypes = () => {
    return payeeTypes.map((dt, i) => {
      return (
        <option value={i} key={i} name={dt}>
          {dt}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-6 mx-auto">
            <div className="card">
              <div className="card-header header">
                <div className="row">
                  <div className="col-md-8 mx-auto">
                    <h3>Edit Payee # {id}</h3>
                  </div>
                  <div className="col-md-4 mx-auto">
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => goBack(e)}
                    >
                      <i className="bi bi-arrow-return-left"></i> Back
                    </Button>
                  </div>
                </div>
                <p></p>{" "}
                {payeeEditResponse && payeeEditResponse.responseCode === -1 ? (
                  <span className="payeeEditError">
                    {payeeEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="payeeEditSuccess">
                    {payeeEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="payeeName">
                        <Form.Label>Payee Name</Form.Label>
                        <Form.Control
                          type="text"
                          value={payee.payeeName}
                          isInvalid={!!errors.payeeName}
                          onChange={(e) =>
                            setField("payeeName", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.payeeName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="payeeACNumber">
                        <Form.Label>Payee A/C Number</Form.Label>
                        <Form.Control
                          type="text"
                          value={payee.payeeACNumber}
                          isInvalid={!!errors.payeeACNumber}
                          onChange={(e) =>
                            setField("payeeACNumber", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.payeeACNumber}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      {showBalance && (
                        <Form.Group controlId="balance">
                          <Form.Label>Balance</Form.Label>
                          <Form.Control
                            className="qtyField"
                            type="text"
                            value={payee.balance}
                            isInvalid={!!errors.balance}
                            onChange={(e) =>
                              setField("balance", e.target.value)
                            }
                          />
                          <Form.Control.Feedback type="invalid">
                            {errors.balance}
                          </Form.Control.Feedback>
                        </Form.Group>
                      )}
                    </div>
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="description">
                        <Form.Label>Description</Form.Label>
                        <Form.Control
                          type="text"
                          value={payee.description}
                          isInvalid={!!errors.description}
                          onChange={(e) =>
                            setField("description", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.description}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="payeeType">
                        <Form.Label>Payee Type</Form.Label>
                        <Form.Control
                          as="select"
                          value={payee.payeeType}
                          isInvalid={!!errors.payeeType}
                          onChange={(e) => {
                            setField("payeeType", e.target.value);
                          }}
                        >
                          <option value="">Select Payee Type</option>
                          {renderOptionsForPayeeTypes()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.payeeType}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Payee
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Payee_Edit;
