// reactapp-pfm/src/components/Bank/Bank.jsx
import React, { useState, useEffect } from "react";
import "./style.css";
import BankService from "../../services/bank.service";
import { getBankColor } from "../../services/local.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import Button from "react-bootstrap/Button";

const Bank = () => {
  let navigate = useNavigate();

  const [banks, setBanks] = useState([]);

  const getAllBanks = () => {
    BankService.allBanks()
      .then((response) => {
        setBanks(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  useEffect(() => {
    getAllBanks();
  }, []);

  const getBankStyle = (row, rowIdx) => {
    var bankColor = getBankColor(row.bankName);
    return { backgroundColor: bankColor };
  };

  const displayBankId = (cell, row) => {
    return (
      <div>
        <span>
          <i className="bi bi-bank"></i> {cell}
        </span>
      </div>
    );
  };
  const displayActionBtn = (cell, row) => {
    // console.log(row);
    return (
      <div>
        {" "}
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => editBank(e, row.bankId)}
        >
          <i className="bi bi-pencil-square"></i>
        </Button>{" "}
        <Button
          className="btn btn-danger"
          type="button"
          onClick={(e) => removeBank(e, row.bankId)}
        >
          <i className="bi bi-trash"></i>
        </Button>{" "}
        <Button
          className="btn btn-success"
          type="button"
          onClick={(e) => getAccounts(e, row.bankId)}
        >
          <i className="bi bi-arrow-bar-right"></i> Accounts
        </Button>
      </div>
    );
  };

  const columns = [
    {
      dataField: "bankId",
      text: "#",
      sort: true,
      formatter: (cell, row) => displayBankId(cell, row),
    },
    {
      dataField: "bankName",
      text: "Bank Name",
      sort: true,
    },
    {
      dataField: "actions",
      text: "Actions",
      formatter: (cell, row) => displayActionBtn(cell, row),
    },
  ];

  const createNewBank = () => {
    navigate("/bank-create");
  };
  const editBank = (e, bankId) => {
    console.log("edit bank : ", bankId);
    navigate("/bank-edit/" + bankId);
  };
  const removeBank = (e, bankId) => {
    console.log("remove bank : ", bankId);
    navigate("/bank-remove/" + bankId);
  };
  const getAccounts = (e, bankId) => {
    console.log("getting accounts for bank : ", bankId);
    navigate("/bank-account-list/" + bankId);
  };

  return (
    <div className="container">
      <div className="mainHeader">Banks</div>
      <hr />
      <div className="row">
        <div className="col-md-2 mx-auto"></div>
        <div className="col-md-8 mx-auto">
          <Button
            className="btn btn-primary"
            type="button"
            onClick={(e) => createNewBank(e)}
          >
            <i className="bi bi-plus-circle"></i> Bank
          </Button>
          <p></p>
          {banks && banks.length > 0 ? (
            <BootstrapTable
              bootstrap4
              keyField="bankId"
              data={banks}
              rowStyle={getBankStyle}
              columns={columns}
              pagination={paginationFactory({ sizePerPage: 5 })}
              filter={filterFactory()}
            />
          ) : (
            <div className="noBanks">No Banks!</div>
          )}
        </div>
        <div className="col-md-2 mx-auto"></div>
      </div>
    </div>
  );
};

export default Bank;

// Angular/src/app/bank/bank.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import Bank from '../models/bank';
import { Observable } from 'rxjs';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-bank',
  templateUrl: './bank.component.html',
  styleUrls: ['./bank.component.css']
})
export class BankComponent implements OnInit {

  banks: Bank[];

  constructor(public localDataService: LocalDataService, public dataService: DataService, private router: Router) { }

  // ok
  ngOnInit() {
    this.banks = [];
    this.loadBanks();
  }

  // ok
  bankRowSetup(banks){
    banks.forEach((element) => {
      element.bgColor = this.localDataService.getBankColor(element.bankName);      
    });
  }

  // ok
  loadBanks() {
    this.dataService.getBanks()
      .subscribe(
        data => {
          this.banks = data;
          this.bankRowSetup(this.banks);

          // banks sort by bank name
          this.banks.sort((a, b) => a.bankName.localeCompare(b.bankName));
        },
        error => {
          console.log(error);
        });
  }

  // ok
  editBank(editedBank){
    this.router.navigate(['/bank-edit/' + editedBank.bankId]);
  }

  // ok
  removeBank(bank){
    console.log(bank);
  }

  // ok
  addBank(){
    // redirect to bank-add component
    this.router.navigate(['/bank-add']);

  }

  // ok
  getBankAccounts(bank){
    this.router.navigate(['/bank-account-list/' + bank.bankId]);
  }

}

<div class="container main-container">
    <div>
        <h2>
            Manage Banks
        </h2>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="card-header header-bg-color">
                   
                    <button type="button" 
                        class="btn btn-primary"
                        (click)="addBank()" >
                        <i class="bi bi-plus-circle"> Bank</i>
                    </button>

                </div>
                <div *ngIf="(banks?.length > 0)" class="card-body">
                    <table class="table table-text ">
                        <thead class="table-header-text">
                            <tr>
                                <th>#</th>
                                <th>Bank Name</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr [ngStyle]="{'background-color': b.bgColor}" 
                                *ngFor="let b of banks" >
                                
                                <td>
                                    <h2><i class="bi bi-bank">{{b.bankId}}</i></h2>
                                </td>
                                <td>
                                    {{b.bankName}}
                                </td>
                             
                                <td>
                                    <div class="row">
                                        <div class="col-1"></div>
                                        <div class="col-2">                                             
                                            <button type="button" 
                                                (click)="editBank(b)" 
                                                class="btn btn-primary"> 
                                                <i class="bi bi-pencil-fill"></i>
                                                                                            
                                            </button>
                                        </div>
                                        <div class="col-1"></div>
                                        <div class="col-2">
                                            <button type="button" 
                                                (click)="removeBank(b)" 
                                                class="btn btn-danger"> 
                                                <i class="bi bi-trash-fill"></i>
                                            </button>
                                        </div>
                                        <div class="col-1"></div>
                                        <div class="col-4">
                                            <button type="button" 
                                                (click)="getBankAccounts(b)" 
                                                class="btn btn-success">
                                                <i class="bi bi-arrow-right"></i> Accounts
                                            </button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div *ngIf="!(banks?.length > 0)" class="card-body no-bank">
                    No Banks Yet !!!
                </div>
            </div>
        </div>
    </div>
</div>
